<?php

/**
 * @file
 * A Drupal 7 custom module that is a block view of a
 * user's username.
 */


/**
 * Implements hook_block_info().
 */
function hellouser_block_info() {
  $blocks['hellouser'] = array(
    'info' => t('Hello User'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function hellouser_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'hellouser':
      $block['subject'] = t('Hello User');
      $block['content'] = hellouser_get_block_text();
      break;
  }
  return $block;
}

/**
 * This is what will be displayed in the block.
 *
 * @return string $output
 *   The block text welcoming the user.
 */
function hellouser_get_block_text() {
  $output = '';

  global $user;
  
  $output .= isset($user->name) ? t('Hello') . ' ' . $user->name . '!' : t('Hello guest!');

  return $output;
}
